In [1]:
import numpy as np


In [2]:
#1. Create a null vector of size 10 but the fifth value which is 1.
ar=np.zeros(10)
ar[4]=1
print(ar)

size=ar.size
print("\nsize",size)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

size 10


In [3]:
#2. Create a vector with values ranging from 10 to 49.
ar=np.arange(10,50)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [4]:
#3. Create a 3x3 matrix with values ranging from 0 to 8
ar=np.arange(0,9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
#4. Find indices of non-zero elements from [1,2,0,0,4,0]
ar = np.array([1,2,0,0,4,0])

print("Original array:")
print(ar)

print("\nIndices of null elements:")
res = np.nonzero(ar == 0)
print(res)

Original array:
[1 2 0 0 4 0]

Indices of null elements:
(array([2, 3, 5], dtype=int64),)


In [6]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
ar=np.random.randn(10,10)
print(ar)

minimum =ar.min()

print("\nThe minimum value is", minimum)

maximum =ar.max()

print("\nThe maximum value is", maximum)

[[-0.56367608  1.04608099 -0.53488775  0.8457926   0.24315212 -0.91673681
   0.03566884 -1.34838193 -0.00890316 -0.02363809]
 [ 1.53657986 -1.86842804  1.19882681 -1.14445491 -0.61146592  0.35916071
  -1.17832871  0.60680316  0.08376011 -2.54101541]
 [-1.61248073 -0.05503289 -0.5411963  -0.676995   -0.23292945  2.72860924
   2.12574387  0.45586644 -0.19196109 -0.41823701]
 [ 0.44578161  1.01143049 -0.97965236  0.2143932  -0.14910015 -1.31113275
  -0.07749852  0.10412734  0.48907347  1.313418  ]
 [-0.70268608  0.59722941 -0.22469695 -0.1598604   0.2708519   0.79934696
   0.36024418 -0.80748591 -0.37888744 -0.6630731 ]
 [ 0.08475521  0.59771739 -1.33820387  0.66522093 -0.47054274 -0.863323
  -0.82662502  0.05678838 -0.64416968 -0.41629596]
 [-1.04910985 -0.20001077 -1.00768409  0.21636616 -0.91103944 -0.11499436
   2.31130154 -1.30570776  1.44621151 -0.97292696]
 [-1.28723171 -1.71962642 -0.5773682   1.40128143  0.17136563  1.17538301
   0.54861136  1.48607481  1.73466464 -0.12702197]
 [

In [7]:
#6. Create a random vector of size 30 and find the mean value.
ar=np.random.random(30)
print(ar)

ne=ar.mean()
print("\nThe mean value is", ne)

[0.46919802 0.62206155 0.69354574 0.4941507  0.05036279 0.00840709
 0.33908926 0.30287073 0.6243753  0.40568348 0.14367071 0.76429745
 0.63312985 0.42505888 0.35072089 0.90698293 0.7402663  0.81614164
 0.97907588 0.73604128 0.80243124 0.73035176 0.87747276 0.42248771
 0.9155443  0.18469421 0.1853625  0.25216228 0.79416751 0.64391372]

The mean value is 0.5437906149328431
